site_name: Sagi's database
site_url: https://sagidb.github.io/
dev_addr: "127.0.0.1:46552"

extra_css:
  - css/custom.css
  - https://fonts.googleapis.com/css2?family=Noto+Serif+SC&family=Noto+Serif:ital,wght@0,100..900;1,100..900&display=swap
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - css/heti.css

extra_javascript:
    - js/heti.js

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.betterem
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
    name: material
    palette:
        scheme: slate
        primary: black
        accent: cyan
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.indexes
        - navigation.path
        - navigation.tabs
        - navigation.top
        - content.code.annotate
        - navigation.tracking
        - header.autohide

plugins:
    - search
    # - git-revision-date-localized
    # - autolinks
    # - section-index
    # - mkdocs-newsletter